import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');

if (!fs.existsSync(distDir)) {
  console.error('Dist directory does not exist:', distDir);
  process.exit(1);
}

// Snapshot original top-level entries generated by ng build
const originalEntries = fs.readdirSync(distDir, { withFileTypes: true })
  .filter(entry => !['browser', 'app', 'ai-chatbot-admin-console', 'build'].includes(entry.name));

const targetDirs = [
  path.join(distDir, 'browser'),
  path.join(distDir, 'app'),
  path.join(distDir, 'app', 'browser'),
  path.join(distDir, 'ai-chatbot-admin-console'),
  path.join(distDir, 'ai-chatbot-admin-console', 'browser'),
  path.join(rootDir, 'build')
];

function copyRecursive(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

for (const target of targetDirs) {
  if (!fs.existsSync(target)) {
    fs.mkdirSync(target, { recursive: true });
  }
  for (const entry of originalEntries) {
    const srcPath = path.join(distDir, entry.name);
    const destPath = path.join(target, entry.name);
    if (entry.isDirectory()) {
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

console.log('✔ Build artifacts successfully synchronized across all target distribution paths.');

